<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType Condition="$([MSBuild]::IsOSPlatform('Windows'))">WinExe</OutputType>
    <OutputType Condition="!$([MSBuild]::IsOSPlatform('Windows'))">Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU;x64</Platforms>
    <Copyright>Copyright © 2026 Sinryou.</Copyright>
    <ApplicationIcon>pimejaSike.ico</ApplicationIcon>
    <PublishProtocol>FileSystem</PublishProtocol>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>True</PublishSingleFile>
    <PublishTrimmed>True</PublishTrimmed>
    <TrimMode>partial</TrimMode>
    <DebugType Condition="'$(Configuration)' == 'Release'">none</DebugType>
    <AssemblyVersion>1.0.2.0</AssemblyVersion>
    <FileVersion>1.0.2.0</FileVersion>
  </PropertyGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Message Text="正在复制 Core 资源文件..." Importance="high" />
    <ItemGroup>
      <SourceAssets Include="$(ProjectDir)Core\**\*.*" />
    </ItemGroup>
    <Copy SourceFiles="@(SourceAssets)" DestinationFiles="$(TargetDir)Core\%(RecursiveDir)%(Filename)%(Extension)" SkipUnchangedFiles="true" OverwriteReadOnlyFiles="true" />
  </Target>

  <Target Name="RemoveNuGetPdbs" AfterTargets="AfterBuild;Publish" Condition="'$(Configuration)' == 'Release'">
    <ItemGroup>
      <_PdbsToRemove Include="$(TargetDir)**\*.pdb" />
    </ItemGroup>
    <Delete Files="@(_PdbsToRemove)" />
  </Target>

  <ItemGroup>
    <Compile Remove="Core\**" />
    <EmbeddedResource Remove="Core\**" />
    <None Remove="Core\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="pimejaSike.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="GtkSharp" Version="3.24.24.95" />
    <PackageReference Include="SkiaSharp" Version="3.119.2" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="3.119.2" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Localization\Strings.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Strings.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Localization\Strings.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Strings.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
