//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTK_ImgsToPDF.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GTK_ImgsToPDF.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Start 的本地化字符串。
        /// </summary>
        internal static string Btn_Start {
            get {
                return ResourceManager.GetString("Btn_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lossy (smaller file, faster generation) 的本地化字符串。
        /// </summary>
        internal static string Check_Lossy {
            get {
                return ResourceManager.GetString("Check_Lossy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Merge sub-PDFs 的本地化字符串。
        /// </summary>
        internal static string Check_Merge {
            get {
                return ResourceManager.GetString("Check_Merge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recursive subfolders 的本地化字符串。
        /// </summary>
        internal static string Check_Recursive {
            get {
                return ResourceManager.GetString("Check_Recursive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select archive file 的本地化字符串。
        /// </summary>
        internal static string Dialog_ArchiveTitle {
            get {
                return ResourceManager.GetString("Dialog_ArchiveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string Dialog_Cancel {
            get {
                return ResourceManager.GetString("Dialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select folder containing images 的本地化字符串。
        /// </summary>
        internal static string Dialog_FolderTitle {
            get {
                return ResourceManager.GetString("Dialog_FolderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        internal static string Dialog_OK {
            get {
                return ResourceManager.GetString("Dialog_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dropped path does not exist 的本地化字符串。
        /// </summary>
        internal static string Drop_NotExist {
            get {
                return ResourceManager.GetString("Drop_NotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dropped file is not a supported archive format 的本地化字符串。
        /// </summary>
        internal static string Drop_NotSupported {
            get {
                return ResourceManager.GetString("Drop_NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All files 的本地化字符串。
        /// </summary>
        internal static string Filter_All {
            get {
                return ResourceManager.GetString("Filter_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Archive files (*.zip, *.rar, *.7z) 的本地化字符串。
        /// </summary>
        internal static string Filter_Archive {
            get {
                return ResourceManager.GetString("Filter_Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PDF has been output to your specified path! 的本地化字符串。
        /// </summary>
        internal static string Hint_Done {
            get {
                return ResourceManager.GetString("Hint_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generating PDF… 的本地化字符串。
        /// </summary>
        internal static string Hint_Generating {
            get {
                return ResourceManager.GetString("Hint_Generating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drag a folder or archive with images here 的本地化字符串。
        /// </summary>
        internal static string Hint_Initial {
            get {
                return ResourceManager.GetString("Hint_Initial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click Start to generate PDF 的本地化字符串。
        /// </summary>
        internal static string Hint_Ready {
            get {
                return ResourceManager.GetString("Hint_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Double Page 的本地化字符串。
        /// </summary>
        internal static string Layout_Duplexlr {
            get {
                return ResourceManager.GetString("Layout_Duplexlr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Double Page R→L 的本地化字符串。
        /// </summary>
        internal static string Layout_Duplexrl {
            get {
                return ResourceManager.GetString("Layout_Duplexrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PDF Layout: 的本地化字符串。
        /// </summary>
        internal static string Layout_Label {
            get {
                return ResourceManager.GetString("Layout_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Single Page 的本地化字符串。
        /// </summary>
        internal static string Layout_Single {
            get {
                return ResourceManager.GetString("Layout_Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About(A) 的本地化字符串。
        /// </summary>
        internal static string Menu_About {
            get {
                return ResourceManager.GetString("Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear Selection(S) 的本地化字符串。
        /// </summary>
        internal static string Menu_ClearSelection {
            get {
                return ResourceManager.GetString("Menu_ClearSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Config File(C) 的本地化字符串。
        /// </summary>
        internal static string Menu_Config {
            get {
                return ResourceManager.GetString("Menu_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit(E) 的本地化字符串。
        /// </summary>
        internal static string Menu_Exit {
            get {
                return ResourceManager.GetString("Menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File(F) 的本地化字符串。
        /// </summary>
        internal static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language(L) 的本地化字符串。
        /// </summary>
        internal static string Menu_Lang {
            get {
                return ResourceManager.GetString("Menu_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Archive(Z) 的本地化字符串。
        /// </summary>
        internal static string Menu_OpenArchive {
            get {
                return ResourceManager.GetString("Menu_OpenArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Folder(O) 的本地化字符串。
        /// </summary>
        internal static string Menu_OpenFolder {
            get {
                return ResourceManager.GetString("Menu_OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Config file not found! 的本地化字符串。
        /// </summary>
        internal static string Msg_ConfigMissing {
            get {
                return ResourceManager.GetString("Msg_ConfigMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error processing folder:  的本地化字符串。
        /// </summary>
        internal static string Msg_ErrProcess {
            get {
                return ResourceManager.GetString("Msg_ErrProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  (no images found) 的本地化字符串。
        /// </summary>
        internal static string Msg_NoImages {
            get {
                return ResourceManager.GetString("Msg_NoImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Waiting for drop… 的本地化字符串。
        /// </summary>
        internal static string Path_Waiting {
            get {
                return ResourceManager.GetString("Path_Waiting", resourceCulture);
            }
        }
    }
}
