<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType Condition="$([MSBuild]::IsOSPlatform('Windows'))">Exe</OutputType>
    <OutputType Condition="!$([MSBuild]::IsOSPlatform('Windows'))">Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <AssemblyTitle>ImgsToPDFCore</AssemblyTitle>
    <Product>ImgsToPDFCore</Product>
    <Platforms>AnyCPU;x64</Platforms>
    <Copyright>Copyright © 2022-2026 Sinryou.</Copyright>
    <ImplicitUsings>enable</ImplicitUsings>
    <PublishProtocol>FileSystem</PublishProtocol>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>True</PublishSingleFile>
    <PublishTrimmed>True</PublishTrimmed>
    <TrimMode>partial</TrimMode>
  </PropertyGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent" Condition="'$(SolutionDir)' != '' and '$(SolutionDir)' != '*Undefined*'">
    <Message Text="正在同步 Core 组件..." Importance="high" />
    <ItemGroup>
      <CoreFiles Include="$(TargetDir)**\*.*" />
    </ItemGroup>
    <Copy
      SourceFiles="@(CoreFiles)"
      DestinationFiles="$(SolutionDir)GTK_ImgsToPDF\Core\%(RecursiveDir)%(Filename)%(Extension)"
      SkipUnchangedFiles="true"
      OverwriteReadOnlyFiles="true" />
  </Target>

  <ItemGroup>
    <PackageReference Include="CommandLineParser" Version="2.9.1" />
    <PackageReference Include="iTextSharp" Version="5.5.13.5" />
    <PackageReference Include="SharpCompress" Version="0.47.4" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.7" />
  </ItemGroup>

  <ItemGroup>
    <None Update="config.lua">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Modules\Common.lua">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Modules\OSUtil.lua">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Modules\PathUtil.lua">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Modules\unicode.lua">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Content Include="libwebp_x64.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="xlua.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="XLua.Mini.dll" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="XLua.Mini">
      <HintPath>XLua.Mini.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>