<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType Condition="$([MSBuild]::IsOSPlatform('Windows'))">WinExe</OutputType>
    <OutputType Condition="!$([MSBuild]::IsOSPlatform('Windows'))">Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <AssemblyTitle>ImgsToPDFCore</AssemblyTitle>
    <Product>ImgsToPDFCore</Product>
    <Platforms>AnyCPU;x64</Platforms>
    <Copyright>Copyright © 2022-2026 Sinryou.</Copyright>
    <ImplicitUsings>enable</ImplicitUsings>
    <PublishProtocol>FileSystem</PublishProtocol>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>True</PublishSingleFile>
    <PublishTrimmed>True</PublishTrimmed>
    <TrimMode>partial</TrimMode>
    <DebugType Condition="'$(Configuration)' == 'Release'">none</DebugType>
  </PropertyGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent" Condition="'$(SolutionDir)' != '' and '$(SolutionDir)' != '*Undefined*'">
    <Message Text="正在同步 Core 组件..." Importance="high" />
    <ItemGroup>
      <CoreFiles Include="$(TargetDir)**\*.*" />
    </ItemGroup>
    <Copy SourceFiles="@(CoreFiles)" DestinationFiles="$(SolutionDir)GTK_ImgsToPDF\Core\%(RecursiveDir)%(Filename)%(Extension)" SkipUnchangedFiles="true" OverwriteReadOnlyFiles="true" />
  </Target>

  <Target Name="RemoveNuGetPdbs" AfterTargets="AfterBuild;Publish" Condition="'$(Configuration)' == 'Release'">
    <ItemGroup>
      <_PdbsToRemove Include="$(TargetDir)**\*.pdb" />
    </ItemGroup>
    <Delete Files="@(_PdbsToRemove)" />
  </Target>

  <ItemGroup>
    <PackageReference Include="CommandLineParser" Version="2.9.1" />
    <PackageReference Include="itext" Version="9.6.0" />
    <PackageReference Include="itext.bouncy-castle-adapter" Version="9.6.0" />
    <PackageReference Include="SharpCompress" Version="0.48.0" />
    <PackageReference Include="SkiaSharp" Version="3.119.2" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="3.119.2" />
  </ItemGroup>

  <ItemGroup>
    <None Update="config.lua">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Modules\Common.lua">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Modules\OSUtil.lua">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Modules\PathUtil.lua">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Modules\unicode.lua">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Modules\VisualGTK.lua">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="xlua.dll" Condition="$([MSBuild]::IsOSPlatform('Windows'))">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="libxlua.so" Condition="!$([MSBuild]::IsOSPlatform('Windows'))">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Content Include="xlua.dll" Condition="$([MSBuild]::IsOSPlatform('Windows'))">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Update="libxlua.so" Condition="!$([MSBuild]::IsOSPlatform('Windows'))">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="XLua.Mini.dll" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="XLua.Mini">
      <HintPath>XLua.Mini.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>